In [ ]:
import os

# Apne Kaggle credentials yahan manually enter karein
os.environ['KAGGLE_USERNAME'] = "upkarchaurasia"
os.environ['KAGGLE_KEY'] = "KGAT_2cdb85cc509e237cdf1476fbb2d32773"

In [ ]:
##!kaggle datasets list -s "loan"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                              title                                       size  lastUpdated                 downloadCount  voteCount  usabilityRating
-----------------------------------------------  ------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
itssuru/loan-data                                Loan Data                                 218250  2021-05-14 19:38:51.467000          17894        174                1
zhijinzhai/loandata                              Loan  Data                                  5608  2017-04-11 02:22:09.320000          30134        339        0.8235294
yasserh/loan-default-dataset                     Loan Default Dataset                     5123932  2022-01-28 16:51:26.070000          31681        243                1
rishikeshkonapure/home-loan-approval             Home Loan Approval                         12880  2023-01-12 06:28:57.770000          21011        162                1
joebeachcapital/loan-default                     Loan Defaults                            2932206  2023-08-02 02:28:22.490000           4635         59                1
vikasukani/loan-eligible-dataset                 Loan Eligible Dataset                      12844  2020-08-15 11:41:07.587000          29442        131                1
ahmadrafiee/bank-personal-loan                   Bank personal loan                         62022  2024-01-01 06:39:16.370000           4421        159        0.9411765
ninzaami/loan-predication                        Loan Predication                            8015  2018-03-11 10:23:38.993000          50172        190       0.64705884
kmldas/loan-default-prediction                   Loan Default Prediction                   111675  2021-04-06 15:03:41.200000          13475        119                1
architsharma01/loan-approval-prediction-dataset  Loan-Approval-Prediction-Dataset           82535  2023-07-16 16:31:20.923000          52767        274                1
bhavikjikadara/loan-status-prediction            Loan Status Prediction                      5336  2024-02-02 13:27:20.870000          15768        111                1
taweilo/loan-approval-classification-data        Loan Approval Classification Dataset      768769  2024-10-29 04:07:34.383000          41194        224                1
mirzahasnine/loan-data-set                       Loan Data Set                              11171  2023-03-12 05:02:43.500000          10870         97        0.9411765
nikhil1e9/loan-default                           Loan Default Prediction Dataset          8240964  2023-09-11 17:58:24.527000          29257        170                1
anishdevedward/loan-approval-dataset             Loan Approval Dataset                      46027  2025-09-23 06:53:26.453000           7171         69                1
prakashraushan/loan-dataset                      Loan-Dataset                              440121  2024-06-07 18:10:54.540000           4664         51        0.8235294
wordsforthewise/lending-club                     All Lending Club loan data            1356507910  2019-04-10 18:03:34.347000         109617        912             0.75
adarshsng/lending-club-loan-data-csv             Lending Club Loan Data                 355544101  2021-06-17 11:06:05.723000          23794        151        0.9411765
teertha/personal-loan-modeling                   Personal Loan Modeling                     62016  2020-03-10 13:20:35.587000          10715         70        0.9411765
rohit265/loan-approval-dataset                   Loan Approval Dataset                   11518904  2024-04-20 08:48:31.057000           4484         47                1

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#anishdevedward/loan-approval-dataset
##%cd /content/drive/MyDrive/dataset

/content/drive/MyDrive/dataset

In [ ]:
# 1. Dataset ko directly is folder me download karein
##!kaggle datasets download -d anishdevedward/loan-approval-dataset

# 2. Download hui zip file ko unzip karein
##!unzip loan-approval-dataset.zip

# 3. Faltu zip file ko delete karein (optional)
##!rm loan-approval-dataset.zip

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/anishdevedward/loan-approval-dataset
License(s): MIT
Downloading loan-approval-dataset.zip to /content/drive/MyDrive/dataset
100% 44.9k/44.9k [00:00<00:00, 5.74MB/s]

Archive:  loan-approval-dataset.zip
  inflating: loan_approval.csv

In [21]:
#Import libraies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#Import pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

#Import imputer
from sklearn.impute import SimpleImputer

#Import scaler
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import OneHotEncoder

#Import model
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
#Load datset
df = pd.read_csv('/content/drive/MyDrive/dataset/loan_approval.csv')

In [4]:
#Check first 10 values
df.head(10)

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
5,Darren Roberts,Port Jesseville,62098,689,19217,29,65.0,True
6,Holly Wood,Lake Joseph,59256,373,40920,40,35.0,False
7,Nicholas Martin,Nelsonside,48289,524,45866,20,25.0,False
8,Patty Perez,Port Leslieview,126530,367,14826,36,55.0,False
9,Emily Rios,Wilkersonmouth,43434,446,18359,8,20.0,False

In [5]:
#About datset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2000 non-null   object
 1   city            2000 non-null   object
 2   income          2000 non-null   int64
 3   credit_score    2000 non-null   int64
 4   loan_amount     2000 non-null   int64
 5   years_employed  2000 non-null   int64
 6   points          2000 non-null   float64
 7   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4), object(2)
memory usage: 111.5+ KB

In [6]:
#Check null values
df.isnull().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [7]:
#Check duplicate values
df.duplicated().sum()

np.int64(0)

In [8]:
#Size of dataset
df.shape

(2000, 8)

In [9]:
df.describe()

              income  credit_score   loan_amount  years_employed       points
count    2000.000000   2000.000000   2000.000000     2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000       20.441000    56.680000
std     34487.874907    160.564945  14207.320147       11.777813    18.638033
min     30053.000000    300.000000   1022.000000        0.000000    10.000000
25%     61296.250000    433.000000  12748.750000       10.000000    45.000000
50%     90387.500000    576.000000  25661.500000       21.000000    55.000000
75%    120099.750000    715.000000  37380.500000       31.000000    70.000000
max    149964.000000    850.000000  49999.000000       40.000000   100.000000

In [23]:
# X feature and Y target column
X = df.drop(columns = 'loan_approved')
y = df['loan_approved']

In [24]:
## Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [20]:
#Differentiate numerical and categorical columns
numeric_col = [col for col in X_train.columns if X_train[col].dtype != 'O']
categorical_col = [col for col in X_train.columns if X_train[col].dtype == 'O']

print(categorical_col)
print(numeric_col)

['name', 'city']
['income', 'credit_score', 'loan_amount', 'years_employed', 'points']

In [35]:
#Pipeline implementation
numeric_pipeline = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'median')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('onehotencoding', OneHotEncoder(handle_unknown='ignore'))
])

transformer = ColumnTransformer(transformers = [
    ('numeric_pipeline', numeric_pipeline, numeric_col),
    ('categorical_pipeline', categorical_pipeline, categorical_col)
])

pipe = Pipeline([
    ('transformer', transformer),
    ('logistic_regression', RandomForestClassifier())
])

In [36]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('numeric_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['income', 'credit_score',
                                                   'loan_amount',
                                                   'years_employed',
                                                   'points']),
                                                 ('categorical_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['name', 'city'])])),
                ('logistic_regression', RandomForestClassifier())])

In [37]:
#Prediction
y_pred = pipe.predict(X_test)

In [38]:
#Acccuracy calculate
accuracy_score(y_test, y_pred)

1.0